/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder: THREE.Mesh
    Cylinder001: THREE.Mesh
    TheBarn: THREE.Mesh
    CubeOneMesh: THREE.Mesh
    CubeOneMesh_1: THREE.Mesh
    Cube: THREE.Mesh
    Cube002: THREE.Mesh
    Cube004: THREE.Mesh
    Cube003: THREE.Mesh
    Cube006: THREE.Mesh
    Cube005: THREE.Mesh
    Cube007: THREE.Mesh
    Cube008: THREE.Mesh
    TheBarn001: THREE.Mesh
    TheBarn002: THREE.Mesh
  }
  materials: {
    ['Material.008']: THREE.MeshStandardMaterial
    ['Material.009']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
    ['Material.007']: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/TheBarnBillboard.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={materials['Material.008']}
        position={[1.25, -3.01, -4.24]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Cylinder001.geometry}
        material={materials['Material.009']}
        position={[1.23, -3.02, -5.03]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        geometry={nodes.TheBarn.geometry}
        material={nodes.TheBarn.material}
        position={[1.25, -2.06, -1.37]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <group position={[1.22, -2.25, -3.29]} scale={[0.09, 1.23, 2.49]}>
        <mesh geometry={nodes.CubeOneMesh.geometry} material={nodes.CubeOneMesh.material} />
        <mesh geometry={nodes.CubeOneMesh_1.geometry} material={materials['Material.003']} />
      </group>
      <mesh
        geometry={nodes.Cube.geometry}
        material={nodes.Cube.material}
        position={[1.22, -3.5, -0.87]}
        scale={[0.08, 1.13, 0.08]}
      />
      <mesh
        geometry={nodes.Cube002.geometry}
        material={nodes.Cube002.material}
        position={[1.22, -3.5, -5.7]}
        scale={[0.08, 1.13, 0.08]}
      />
      <mesh
        geometry={nodes.Cube004.geometry}
        material={nodes.Cube004.material}
        position={[0.44, -3.04, -0.86]}
        rotation={[0, 0, -0.44]}
        scale={[0.08, 1.77, 0.08]}
      />
      <mesh
        geometry={nodes.Cube003.geometry}
        material={nodes.Cube003.material}
        position={[0.44, -3.04, -5.71]}
        rotation={[0, 0, -0.44]}
        scale={[0.08, 1.77, 0.08]}
      />
      <mesh
        geometry={nodes.Cube006.geometry}
        material={nodes.Cube006.material}
        position={[-0.15, -3.5, -12.98]}
        scale={[0.08, 1.56, 0.08]}
      />
      <mesh
        geometry={nodes.Cube005.geometry}
        material={nodes.Cube005.material}
        position={[0.28, -3.37, -3.27]}
        rotation={[-Math.PI / 2, 0.43, 0]}
        scale={[0.08, 2.38, 0.08]}
      />
      <mesh
        geometry={nodes.Cube007.geometry}
        material={nodes.Cube007.material}
        position={[1.09, -1.68, -3.28]}
        rotation={[-Math.PI / 2, 0.46, 0]}
        scale={[0.08, 2.38, 0.08]}
      />
      <mesh
        geometry={nodes.Cube008.geometry}
        material={materials['Material.004']}
        position={[0.44, -3.04, -3.31]}
        rotation={[0, 0, -0.44]}
        scale={[0.08, 1.77, 0.08]}
      />
      <mesh
        geometry={nodes.TheBarn001.geometry}
        material={materials['Material.006']}
        position={[1.25, -2.38, -1.21]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.TheBarn002.geometry}
        material={materials['Material.007']}
        position={[1.25, -2.91, -1.21]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
    </group>
  )
}

useGLTF.preload('/TheBarnBillboard.glb')
